version: '3'
services:
  app:
    container_name: server
    build:
      args:
        PORT: ${PORT}
        MONGO_URI: ${MONGO_URI}
        JWT_SECRET: ${JWT_SECRET}
        REFRESH_SECRET: ${REFRESH_SECRET}
        EMAIL: ${EMAIL}
        PASS: ${PASS}
    ports:
      - "3000:3000"
    env_file:
      - .env
